using UniversityProcessing.Abstractions.Http.Universities.University;
using UniversityProcessing.GenericSubdomain.Pagination;

namespace UniversityProcessing.DomainServices.Features.UniversityPositions.GetList;

public sealed record GetUniversityPositionsQueryResponse(PagedList<UniversityPositionDto> List);
