using UniversityProcessing.Domain.UniversityStructure;
using UniversityProcessing.GenericSubdomain.Pagination;

namespace UniversityProcessing.DomainServices.Features.UniversityPositions.GetList;

public sealed record GetUniversityPositionsQueryResponse(PagedList<UniversityPosition> List);
