using UniversityProcessing.GenericSubdomain.Pagination;

namespace UniversityProcessing.Abstractions.Http.Universities.DiplomaPeriods;

public sealed class GetActualDiplomaPeriodsRequestDto : BaseGetListQueryParameters;
