using UniversityProcessing.Abstractions.Http.Universities.University;

namespace UniversityProcessing.DomainServices.Features.UniversityPositions.Get;

public sealed record GetUniversityPositionQueryResponse(UniversityPositionDto UniversityPosition);
