using UniversityProcessing.Domain.UniversityStructure;

namespace UniversityProcessing.DomainServices.Features.UniversityPositions.Get;

public sealed record GetUniversityPositionQueryResponse(UniversityPosition UniversityPosition);
