using MediatR;

namespace UniversityProcessing.DomainServices.Features.Identity.RegisterStudent.GetRegisterStudentAvailableGroups;

public sealed record GetRegisterStudentAvailableGroupsQueryRequest(string Number) : IRequest<GetRegisterStudentAvailableGroupsQueryResponse>;
