using MediatR;

namespace UniversityProcessing.DomainServices.Features.Identity.RegisterEmployee.GetRegisterEmployeeAvailableUniversityPositions;

public sealed record GetRegisterEmployeeAvailableUniversityPositionsQueryRequest : IRequest<GetRegisterEmployeeAvailableUniversityPositionsQueryResponse>;
