using UniversityProcessing.Abstractions.Http.Universities;
using UniversityProcessing.Abstractions.Http.Universities.University;
using UniversityProcessing.GenericSubdomain.Pagination;

namespace UniversityProcessing.DomainServices.Features.UniversityPositions.List.Contracts;

public sealed record UniversityPositionListQueryResponse(PagedList<UniversityPositionDto> List);